export const START_LOAD = 'START_LOAD';
export const END_LOAD = 'END_LOAD';
export const CLOSE_SYS_POPUP = 'CLOSE_SYS_POPUP';
export const OPEN_SYS_POPUP = 'OPEN_SYS_POPUP';
export const SET_STATE = 'SET_STATE';
export const CHANGE_SYSTEM_STATE = 'CHANGE_SYSTEM_STATE';
export const SET_SYS_STATE = 'SET_SYS_STATE';
export const GET_SYS_STATE = 'GET_SYS_STATE';
// navbar
export const NAVBAR_TOGGLE = 'NAVBAR_TOGGLE';
export const NAVBAR_OPEN = 'NAVBAR_OPEN';
export const NAVBAR_CLOSE = 'NAVBAR_CLOSE';
export const NAVBAR_OPENED = 'NAVBAR_OPENED';
export const NAVBAR_CLOSED = 'NAVBAR_CLOSED';
export const NAVBAR_SET_ACTIVE = 'NAVBAR_SET_ACTIVE';
export const NAVBAR_ACTIVE_CHANGED = 'NAVBAR_ACTIVE_CHANGED';
export const NAVBAR_FIRST_PANEL_OPENED = 'NAVBAR_FIRST_PANEL_OPENED';
export const NAVBAR_FIRST_PANEL_CLOSED = 'NAVBAR_FIRST_PANEL_CLOSED';
export const NAVBAR_FIXED_TOGGLE = 'NAVBAR_FIXED_TOGGLE';
export const TOGGLE_APP_MODAL = 'TOGGLE_APP_MODAL';

// user
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const USER_LOGGED_ERROR = 'USER_LOGGED_ERROR';
export const USER_CHECKAUTH = 'USER_CHECKAUTH';
export const CHANGE_LOCALE = 'CHANGE_LOCALE';
export const USER_CHECK = 'USER_CHECK';

//filters
export const FILTERS_CHANGE = 'FILTERS_CHANGE';
export const FILTERS_CHANGED = 'FILTERS_CHANGED';
export const GET_FILTERS = 'GET_FILTERS';
export const FILTERS_LOADED = 'FILTERS_LOADED';
export const FILTERS_LOAD = 'FILTERS_LOAD';
export const FILTERS_LOAD_ERROR = 'FILTERS_LOAD_ERROR';
export const FILTERS_DEFAULT = 'FILTERS_DEFAULT';

//marketing
export const MARKETING_LOAD_DATA = 'MARKETING_LOAD_DATA';
export const MARKETING_AOB_DATA_LOADED = 'MARKETING_AOB_DATA_LOADED';
export const MARKETING_IF_DATA_LOADED = 'MARKETING_IF_DATA_LOADED';
export const MARKETING_SF_DATA_LOADED = 'MARKETING_SF_DATA_LOADED';
export const MARKETING_MP_DATA_LOADED = 'MARKETING_MP_DATA_LOADED';
export const MARKETING_RS_DATA_LOADED = 'MARKETING_RS_DATA_LOADED';
export const MARKETING_AL_DATA_LOADED = 'MARKETING_AL_DATA_LOADED';
export const MARKETING_IFL_DATA_LOADED = 'MARKETING_IFL_DATA_LOADED';

export const MARKETING_AOB_UPDATE = 'MARKETING_AOB_UPDATE';
export const MARKETING_AOB_UPDATED = 'MARKETING_AOB_UPDATED';

//plan-fact
export const PLANFACT_LOAD_DATA = 'PLANFACT_LOAD_DATA';
export const PLANFACT_SALES_PLAN_LOADED = 'PLANFACT_SALES_PLAN_LOADED';
export const PLANFACT_CREDIT_STATS_LOADED = 'PLANFACT_CREDIT_STATS_LOADED';
export const PLANFACT_INSURANSE_PRODUCT_LOADED =
	'PLANFACT_INSURANSE_PRODUCT_LOADED';
export const PLANFACT_BANKS_PLAN_LOADED = 'PLANFACT_BANKS_PLAN_LOADED';
export const PLANFACT_SALES_PLAN_LOAD = 'PLANFACT_SALES_PLAN_LOAD';
export const PLANFACT_CREDIT_STATS_LOAD = 'PLANFACT_CREDIT_STATS_LOAD';
export const PLANFACT_INSURANSE_PRODUCT_LOAD =
	'PLANFACT_INSURANSE_PRODUCT_LOAD';
export const PLANFACT_BANKS_PLAN_LOAD = 'PLANFACT_BANKS_PLAN_LOAD';


//bank-efficiency
export const BANK_EFF_LOAD_DATA = 'BANK_EFF_LOAD_DATA';
export const BANK_EFF_EFFICIENCY_LOADED = 'BANK_EFF_EFFICIENCY_LOADED';
export const BANK_EFF_EFFICIENCY_GROUPED_LOADED =
	'BANK_EFF_EFFICIENCY_GROUPED_LOADED';
export const BANK_EFF_DEALER_LOADED = 'BANK_EFF_DEALER_LOADED';
export const BANK_EFF_REGISTRY_RIVIEW_LOADED =
	'BANK_EFF_REGISTRY_RIVIEW_LOADED';
export const BANK_EFF_EFFICIENCY_LOAD = 'BANK_EFF_EFFICIENCY_LOAD';
export const BANK_EFF_EFFICIENCY_GROUPED_LOAD =
	'BANK_EFF_EFFICIENCY_GROUPED_LOAD';
export const BANK_EFF_REGISTRY_RIVIEW_LOAD = 'BANK_EFF_REGISTRY_RIVIEW_LOAD';
export const BANK_EFF_SORT_DATA = 'BANK_EFF_SORT_DATA';
export const BANK_EFF_DEALER_LOAD = 'BANK_EFF_DEALER_LOAD';

//employee-performance
export const EMPLPERF_LOAD_DATA = 'EMPLPERF_LOAD_DATA';
export const EMPLPERF_ACTIVITY_LOADED = 'EMPLPERF_ACTIVITY_LOADED';
export const EMPLPERF_CS_EFF_LOADED = 'EMPLPERF_CS_EFF_LOADED';
export const EMPLPERF_CS_EFF_GR_LOADED = 'EMPLPERF_CS_EFF_GR_LOADED';
export const EMPLPERF_SM_EFF_LOADED = 'EMPLPERF_SM_EFF_LOADED';
export const EMPLPERF_SM_EFF_GR_LOADED = 'EMPLPERF_SM_EFF_GR_LOADED';
export const EMPLPERF_MPP_EFF_LOADED = 'EMPLPERF_MPP_EFF_LOADED';
export const EMPLPERF_MPP_EFF_GR_LOADED = 'EMPLPERF_MPP_EFF_GR_LOADED';
export const EMPLPERF_CS_EFF_LOAD = 'EMPLPERF_CS_EFF_LOAD';
export const EMPLPERF_CS_EFF_GR_LOAD = 'EMPLPERF_CS_EFF_GR_LOAD';
export const EMPLPERF_SM_EFF_LOAD = 'EMPLPERF_SM_EFF_LOAD';
export const EMPLPERF_SM_EFF_GR_LOAD = 'EMPLPERF_SM_EFF_GR_LOAD';
export const EMPLPERF_MPP_EFF_LOAD = 'EMPLPERF_MPP_EFF_LOAD';
export const EMPLPERF_MPP_EFF_GR_LOAD = 'EMPLPERF_MPP_EFF_GR_LOAD';
export const EMPLPERF_USER_ACTIVITY_LOADED = 'EMPLPERF_USER_ACTIVITY_LOADED';
export const EMPLPERF_DEALER_ACTIVITY_LOADED =
	'EMPLPERF_DEALER_ACTIVITY_LOADED';
export const EMPLPERF_USER_ACTIVITY_LOAD = 'EMPLPERF_USER_ACTIVITY_LOAD';
export const EMPLPERF_DEALER_ACTIVITY_LOAD = 'EMPLPERF_DEALER_ACTIVITY_LOAD';

//profit
export const PROFIT_PRODUCTS_REVENUE_LOAD = 'PROFIT_PRODUCTS_REVENUE_LOAD';
export const PROFIT_PRODUCTS_REVENUE_LOADED = 'PROFIT_PRODUCTS_REVENUE_LOADED';
export const PROFIT_BANKS_PLAN_LOAD = 'PROFIT_BANKS_PLAN_LOAD';
export const PROFIT_BANKS_PLAN_LOADED = 'PROFIT_BANKS_PLAN_LOADED';
export const PROFIT_INSURERS_PLAN_LOAD = 'PROFIT_INSURERS_PLAN_LOAD';
export const PROFIT_INSURERS_PLAN_LOADED = 'PROFIT_INSURERS_PLAN_LOADED';
export const PROFIT_BANK_COMISSIONS_LOAD = 'PROFIT_BANK_COMISSIONS_LOAD';
export const PROFIT_BANK_COMISSIONS_LOADED = 'PROFIT_BANK_COMISSIONS_LOADED';
export const PROFIT_GAP_COMISSIONS_LOAD = 'PROFIT_GAP_COMISSIONS_LOAD';
export const PROFIT_GAP_COMISSIONS_LOADED = 'PROFIT_GAP_COMISSIONS_LOADED';
export const PROFIT_PPI_COMISSIONS_LOAD = 'PROFIT_PPI_COMISSIONS_LOAD';
export const PROFIT_PPI_COMISSIONS_LOADED = 'PROFIT_PPI_COMISSIONS_LOADED';
export const PROFIT_KASKO_COMISSIONS_LOAD = 'PROFIT_KASKO_COMISSIONS_LOAD';
export const PROFIT_KASKO_COMISSIONS_LOADED = 'PROFIT_KASKO_COMISSIONS_LOADED';
export const PROFIT_DEALER_SERVICE_COMMISSIONS_LOAD =
	'PROFIT_DEALER_SERVICE_COMMISSIONS_LOAD';
export const PROFIT_DEALER_SERVICE_COMMISSIONS_LOADED =
	'PROFIT_DEALER_SERVICE_COMMISSIONS_LOADED';
export const PROFIT_BANK_SERVICE_COMMISSIONS_LOAD =
	'PROFIT_BANK_SERVICE_COMMISSIONS_LOAD';
export const PROFIT_BANK_SERVICE_COMMISSIONS_LOADED =
	'PROFIT_BANK_SERVICE_COMMISSIONS_LOADED';
export const PROFIT_ADDITIONAL_DEALER_SERVICE_COMMISSIONS_LOAD =
	'PROFIT_ADDITIONAL_DEALER_SERVICE_COMMISSIONS_LOAD';
export const PROFIT_ADDITIONAL_DEALER_SERVICE_COMMISSIONS_LOADED =
	'PROFIT_ADDITIONAL_DEALER_SERVICE_COMMISSIONS_LOADED';
export const PROFIT_APPLICATION_REGISTRY_LOAD =
	'PROFIT_APPLICATION_REGISTRY_LOAD';
export const PROFIT_APPLICATION_REGISTRY_LOADED =
	'PROFIT_APPLICATION_REGISTRY_LOADED';
export const PROFIT_LOAD_DATA = 'PROFIT_LOAD_DATA';

//sales-performancce
export const SALES_FUNNEL_LOAD = 'SALES_FUNNEL_LOAD';
export const SALES_FUNNEL_LOADED = 'SALES_FUNNEL_LOADED';
export const SHORT_SUMMARY_LOAD = 'SHORT_SUMMARY_LOAD';
export const SHORT_SUMMARY_LOADED = 'SHORT_SUMMARY_LOADED';
export const CREDIT_TERMS_LOAD = 'CREDIT_TERMS_LOAD';
export const CREDIT_TERMS_LOADED = 'CREDIT_TERMS_LOADED';
export const BANKS_STATS_LOAD = 'BANKS_STATS_LOAD';
export const BANKS_STATS_LOADED = 'BANKS_STATS_LOADED';
export const KASKO_STATS_LOAD = 'KASKO_STATS_LOAD';
export const KASKO_STATS_LOADED = 'KASKO_STATS_LOADED';
export const PPI_STATS_LOAD = 'PPI_STATS_LOAD';
export const PPI_STATS_LOADED = 'PPI_STATS_LOADED';
export const GAP_STATS_LOAD = 'GAP_STATS_LOAD';
export const GAP_STATS_LOADED = 'GAP_STATS_LOADED';
export const ADDITIONAL_SERVICES_STATS_LOAD = 'ADDITIONAL_SERVICES_STATS_LOAD';
export const ADDITIONAL_SERVICES_STATS_LOADED = 'ADDITIONAL_SERVICES_STATS_LOADED';
export const ADDITIONAL_BANK_SERVICES_STATS_LOAD = 'ADDITIONAL_BANK_SERVICES_STATS_LOAD';
export const ADDITIONAL_BANK_SERVICES_STATS_LOADED = 'ADDITIONAL_BANK_SERVICES_STATS_LOADED';
export const SHARE_MODELS_LOANS_LOAD = 'SHARE_MODELS_LOANS_LOAD';
export const SHARE_MODELS_LOANS_LOADED = 'SHARE_MODELS_LOANS_LOADED';
export const CREDIT_STATS_LOAD = 'CREDIT_STATS_LOAD';
export const CREDIT_STATS_LOADED = 'CREDIT_STATS_LOADED';
export const TOP_DEALERS_LOAD = 'TOP_DEALERS_LOAD';
export const TOP_DEALERS_LOADED = 'TOP_DEALERS_LOADED';
export const TOP_MODELS_LOAD = 'TOP_MODELS_LOAD';
export const TOP_MODELS_LOADED = 'TOP_MODELS_LOADED';
export const DAILY_STATISTICS_LOAD = 'DAILY_STATISTICS_LOAD';
export const DAILY_STATISTICS_LOADED = 'DAILY_STATISTICS_LOADED';
export const DAILY_STATISTICS_BY_WEEKS_LOAD = 'DAILY_STATISTICS_BY_WEEKS_LOAD';
export const DAILY_STATISTICS_BY_WEEKS_LOADED = 'DAILY_STATISTICS_BY_WEEKS_LOADED';
export const DAILY_STATISTICS_BY_MONTHS_LOAD = 'DAILY_STATISTICS_BY_MONTHS_LOAD';
export const DAILY_STATISTICS_BY_MONTHS_LOADED = 'DAILY_STATISTICS_BY_MONTHS_LOADED';
export const EXECUTION_SALES_PLAN_NEW_LOAD = 'EXECUTION_SALES_PLAN_NEW_LOAD';
export const EXECUTION_SALES_PLAN_NEW_LOADED = 'EXECUTION_SALES_PLAN_NEW_LOADED';
export const EXECUTION_SALES_PLAN_USED_LOAD = 'EXECUTION_SALES_PLAN_USED_LOAD';
export const EXECUTION_SALES_PLAN_USED_LOADED = 'EXECUTION_SALES_PLAN_USED_LOADED';
export const PRODUCT_PENETRATION_STATS_LOAD = 'PRODUCT_PENETRATION_STATS_LOAD';
export const PRODUCT_PENETRATION_STATS_LOADED = 'PRODUCT_PENETRATION_STATS_LOADED';
export const SALES_LOAD_DATA = "SALES_LOAD_DATA";
export const BANKS_STATS_SORTED_LOAD = 'BANKS_STATS_SORTED_LOAD';
export const BANKS_STATS_SORTED_LOADED = 'BANKS_STATS_SORTED_LOADED';

//
export const SALESDIFF_LOAD_DATA = 'SALESDIFF_LOAD_DATA';
export const SALESDIFF_DATA_LOADED = 'SALESDIFF_DATA_LOADED';
export const SALESDIFF_UPDATE = 'SALESDIFF_UPDATE';
export const SALESDIFF_DATA_FETCHIG = 'SALESDIFF_DATA_FETCHIG';
export const SALESDIFF_SET_EDIT_MODE='SALESDIFF_SET_EDIT_MODE';

// report
export const REPORT_LOAD = 'REPORT_LOAD';
export const REPORT_LOADED = 'REPORT_LOADED';

// app-dop
export const APP_DOP_START_LOAD='APP_DOP_START_LOAD';
export const APP_DOP_END_LOAD='APP_DOP_END_LOAD';
export const APP_DOP_LOAD_DATA='APP_DOP_LOAD_DATA';
export const AOP_DOP_LOADED = 'AOP_DOP_LOADED';
export const APP_DOP_ADD_CHANGED='APP_DOP_ADD_CHANGED';
export const APP_DOP_DROP='APP_DOP_DROP';

// Financed partners filters (in popup)
export const FINANCIAL_PARTNERS_START_LOAD='FINANCIAL_PARTNERS_START_LOAD';
export const FINANCIAL_PARTNERS_LOAD_DATA='FINANCIAL_PARTNERS_LOAD_DATA';
export const FINANCIAL_PARTNERS_LOADED='FINANCIAL_PARTNERS_LOADED';
export const ISSUED_INSURANCES_START_LOAD='ISSUED_INSURANCES_START_LOAD';
export const ISSUED_INSURANCES_LOAD_DATA='ISSUED_INSURANCES_LOAD_DATA';
export const ISSUED_INSURANCES_LOADED='ISSUED_INSURANCES_LOADED';